/**
 * دفعة وصفات دايت حقيقية إضافية — مصدرها الرسمي: USDA MyPlate Kitchen (مجموعة وصفات وزارة
 * الزراعة الأمريكية للتوعية الغذائية، Public Domain)، عبر واجهة myplate.food/api (نسخة مرآة
 * لمجموعة myplate.gov الأصلية بعد إيقافها 2026-01-07). القيم الغذائية (سعرات/بروتين/كارب/دهون)
 * محسوبة رسميًا من USDA، لم تُخترع هنا. الترجمة للعربية العراقية والمكونات/الخطوات منقولة بمعنى
 * الوصفة الأصلية (مو ترجمة حرفية آلية) لتناسب لهجة التطبيق. لا صور — نفس تصميم recipes_seed.py
 * الأصلي (تُعرض أيقونة تصنيف بديلة بدون صورة).
 *
 * المصدر لكل وصفة: https://myplate.food/recipes/<slug> (راجع source_url بكل عنصر أدناه).
 */

export interface ExtraRecipeSeed {
  name: string; slug: string; category: string; description: string;
  prep_time_min: number; cook_time_min: number; servings: number; difficulty: "easy" | "medium" | "hard";
  calories: number; protein: number; carbs: number; fat: number; fiber: number | null;
  match_keywords: string[];
  ingredients: { name: string; quantity: string | null; unit: string | null }[];
  steps: { instruction: string; duration: string | null; temperature: string | null; tip: string | null; warning: string | null }[];
  substitutions: Record<string, string>;
  source_url: string;
}

const s = (instruction: string, duration: string | null = null, temperature: string | null = null, tip: string | null = null, warning: string | null = null) =>
  ({ instruction, duration, temperature, tip, warning });
const i = (name: string, quantity: string | null, unit: string | null) => ({ name, quantity, unit });

export const EXTRA_RECIPES_SEED: ExtraRecipeSeed[] = [
  // ==================== فطور ====================
  {
    name: "بيض مسلوق محشي (ديفلد إكز)", slug: "heavenly-deviled-eggs", category: "فطور",
    description: "فطور سريع غني بالبروتين — بيض مسلوق محشي بخليط المايونيز والخردل.",
    prep_time_min: 10, cook_time_min: 12, servings: 6, difficulty: "easy",
    calories: 84, protein: 6.2, carbs: 1, fat: 6.2, fiber: 0,
    match_keywords: ["بيض محشي", "ديفلد ايكز", "بيض مسلوق"],
    ingredients: [i("بيض", "6", "حبة بقشرها"), i("مايونيز قليل الدسم", "2", "ملعقة كبيرة"), i("خردل", "1", "ملعقة صغيرة")],
    steps: [
      s("اغسل ايدينك بالصابون. حط البيض بقدر وغطيه بماي بارد.", null, null, null, null),
      s("خله يغلي على نار هادئة 12 دقيقة، بعدين صفّيه وبرّده تحت الماي البارد.", "12 دقيقة", null, null, null),
      s("قشّر البيض، شقّه نصين طولي، واطلع الصفار.", null, null, null, null),
      s("اهرس الصفار مع المايونيز والخردل وحشي بيه نص البيضة البيضاء.", null, null, "تكدر تحط الخليط بكيس بلاستيك وتقص طرفه لحشي أنظف.", null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/heavenly-deviled-eggs",
  },
  {
    name: "شيك فواكه وزبادي للفطور", slug: "fruit-and-yogurt-breakfast-shake", category: "فطور",
    description: "مشروب فطور سريع بالخلاط، جرّبه بأي فواكه موسمية تحبها.",
    prep_time_min: 5, cook_time_min: 0, servings: 2, difficulty: "easy",
    calories: 168, protein: 4.2, carbs: 35.2, fat: 1.3, fiber: 1.9,
    match_keywords: ["شيك فواكه", "سموذي فطور", "شيك زبادي"],
    ingredients: [i("موز ناضج", "1", "حبة متوسطة مقشرة"), i("عصير أناناس", "3/4", "كوب"), i("زبادي فانيلا قليل الدسم", "1/2", "كوب"), i("فراولة", "1/2", "كوب")],
    steps: [s("اخفق كل المكونات بالخلاط لين تنعّم.", null, null, null, null), s("وزّعه على كاسين وقدّمه فورًا.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/fruit-and-yogurt-breakfast-shake",
  },
  {
    name: "توست فرنسي", slug: "fantastic-french-toast", category: "فطور",
    description: "فطور كلاسيكي بسيط، قدّمه مع فواكه طازجة أو معلبة.",
    prep_time_min: 10, cook_time_min: 12, servings: 6, difficulty: "easy",
    calories: 123, protein: 7.2, carbs: 16.7, fat: 3, fiber: 2.2,
    match_keywords: ["توست فرنسي", "خبز محمر بالبيض"],
    ingredients: [i("بيض كبير", "2", "حبة"), i("حليب خالي الدسم", "1/2", "كوب"), i("فانيلا", "1/2", "ملعقة صغيرة"), i("خبز قمح كامل", "6", "أرغفة"), i("عسل أو شراب", null, "حسب الرغبة")],
    steps: [
      s("اخفق البيض والحليب والفانيلا سوا بوعاء لين يتجانس.", null, null, null, null),
      s("سخّن مقلاة على نار متوسطة وادهنها بشوية زيت.", null, "نار متوسطة", null, null),
      s("غمّس كل رغيف بالخليط من الجهتين واقلي لين يصير لونه ذهبي، حوالي 4 دقايق لكل وجه.", "4 دقايق لكل وجه", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/fantastic-french-toast",
  },
  {
    name: "دقيق الشوفان بالفواكه", slug: "fruity-homemade-oatmeal", category: "فطور",
    description: "وجبة شوفان دافئة بالتفاح والقرفة، مثالية للصباح البارد.",
    prep_time_min: 10, cook_time_min: 5, servings: 2, difficulty: "easy",
    calories: 208, protein: 4.5, carbs: 44.1, fat: 2.1, fiber: 6.3,
    match_keywords: ["شوفان بالفواكه", "دقيق شوفان", "عصيدة شوفان"],
    ingredients: [i("تفاح", "1", "حبة مقشرة ومقطعة"), i("قرفة", "1", "ملعقة صغيرة"), i("زبيب", "2", "ملعقة كبيرة"), i("شوفان", "3/4", "كوب"), i("ماي", "1.5", "كوب")],
    steps: [
      s("قشّر التفاح وقطّعه قطع صغيرة.", null, null, null, null),
      s("حط الماي بقدر وخله يغلي على نار متوسطة.", null, "نار متوسطة", null, null),
      s("زيد الشوفان والزبيب والتفاح والقرفة، وخفف النار.", null, null, null, null),
      s("اطبخه 5 دقايق وحرّكه باستمرار.", "5 دقايق", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/fruity-homemade-oatmeal",
  },
  {
    name: "بان كيك بشرائح التفاح", slug: "apple-slice-pancakes", category: "فطور",
    description: "بان كيك عادي بلمسة تفاح وقرفة تخليه ألذ وأخف.",
    prep_time_min: 10, cook_time_min: 15, servings: 6, difficulty: "medium",
    calories: 151, protein: 4.8, carbs: 25.5, fat: 3.2, fiber: 2.2,
    match_keywords: ["بان كيك تفاح", "فطائر تفاح"],
    ingredients: [i("تفاح أخضر", "1", "حبة"), i("خليط بان كيك", "1.25", "كوب"), i("قرفة", "1/2", "ملعقة صغيرة"), i("بيض كبير", "1", "حبة"), i("زيت كانولا", "2", "ملعقة صغيرة"), i("حليب قليل الدسم", "1", "كوب")],
    steps: [
      s("قشّر التفاح وقطّعه حلقات رقيقة.", null, null, null, null),
      s("اخلط باقي المكونات سوا بوعاء لين يتجانس (تقبل شوية كتل صغيرة).", null, null, "لا تخلط زيادة حتى يظل البان كيك طري.", null),
      s("سخّن مقلاة، حط حلقة تفاح وصب فوگها ربع كوب خليط.", null, "نار متوسطة", null, null),
      s("اطبخه لين تطلع فقاعات، بعدين اقلبه واطبخ الوجه الثاني لين يصير ذهبي.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/apple-slice-pancakes",
  },
  {
    name: "شوفان بالموز والجوز", slug: "banana-walnut-oatmeal", category: "فطور",
    description: "شوفان كريمي بالموز المهروس والجوز، فطور مشبع وسهل.",
    prep_time_min: 5, cook_time_min: 5, servings: 4, difficulty: "easy",
    calories: 304, protein: 10.4, carbs: 54.5, fat: 5.3, fiber: 5.4,
    match_keywords: ["شوفان بالموز", "شوفان بالجوز"],
    ingredients: [i("حليب", "2", "كوب"), i("ملح", null, "رشة، اختياري"), i("ماي", "2.75", "كوب"), i("شوفان سريع التحضير", "2", "كوب"), i("موز ناضج مهروس", "2", "حبة"), i("شراب القيقب", "2", "ملعقة كبيرة"), i("جوز مفروم", "2", "ملعقة كبيرة")],
    steps: [
      s("سخّن الحليب والملح والماي بقدر صغير على نار متوسطة لين يصير حار بس مو يغلي.", null, "نار متوسطة", null, null),
      s("زيد الشوفان وحرّكه لين يصير كريمي، دقيقة إلى دقيقتين.", "1-2 دقيقة", null, null, null),
      s("ارفعه عن النار وزيد الموز المهروس وشراب القيقب.", null, null, null, null),
      s("وزّعه على 4 اطباق وزيّنه بالجوز المفروم.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/banana-walnut-oatmeal",
  },
  {
    name: "خلطة فطور بالقرفة والزبيب", slug: "cinnamon-raisin-breakfast-mix", category: "فطور",
    description: "خلطة حبوب فطور سريعة بالمايكروويف، عبيها بأكياس صغيرة لفطور سريع بره البيت.",
    prep_time_min: 10, cook_time_min: 4, servings: 10, difficulty: "easy",
    calories: 139, protein: 1.9, carbs: 25.3, fat: 3.7, fiber: 2.2,
    match_keywords: ["خلطة فطور", "كورن فليكس بالقرفة"],
    ingredients: [i("سكر", "1/4", "كوب"), i("قرفة مطحونة", "1", "ملعقة صغيرة"), i("سمن نباتي طري", "1/4", "كوب"), i("حبوب ذرة كاملة", "1.5", "كوب"), i("حبوب رز كاملة", "1.5", "كوب"), i("حبوب قمح كاملة", "1.5", "كوب"), i("زبيب أو توت مجفف", "1/2", "كوب")],
    steps: [
      s("اخلط السكر والقرفة بوعاء صغير وخله جنب.", null, null, null, null),
      s("ذوّب السمن بالمايكروويف حوالي 40 ثانية.", "40 ثانية", null, null, null),
      s("زيد الحبوب الثلاثة وقلّبها لين تتغطى بالسمن.", null, null, null, null),
      s("شغّل المايكروويف دقيقتين وحرّك بعد أول دقيقة، بعدين رش خليط السكر وقرّب دقيقة زيادة.", "2 دقيقة", null, null, null),
      s("زيد الزبيب وافردها على منشفة ورقية حتى تبرد.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/cinnamon-raisin-breakfast-mix",
  },
  {
    name: "فريتاتا سبانخ فرنسية", slug: "french-spinach-frittata", category: "فطور",
    description: "طبق بيض بالفرن مع سبانخ وجبنة فيتا، فطور غني بالبروتين.",
    prep_time_min: 10, cook_time_min: 30, servings: 6, difficulty: "medium",
    calories: 132, protein: 9.6, carbs: 1.9, fat: 9.6, fiber: 0.4,
    match_keywords: ["فريتاتا سبانخ", "بيض بالفرن بالسبانخ"],
    ingredients: [i("بيض", "8", "حبة"), i("ملح", "1/2", "ملعقة صغيرة"), i("فلفل أسود", "1/2", "ملعقة صغيرة"), i("سبانخ", "2", "كوب مفرومة ناعم"), i("بصل أخضر", "4", "حبة مقطعة"), i("جبنة فيتا مفتتة", "1/4", "كوب"), i("زيت نباتي", "2", "ملعقة صغيرة")],
    steps: [
      s("سخّن الفرن.", null, "180°م", null, null),
      s("اخفق البيض مع الملح والفلفل بوعاء لين يتجانس.", null, null, null, null),
      s("زيد البصل الأخضر والسبانخ وجبنة الفيتا وقلّب.", null, null, null, null),
      s("سخّن مقلاة تتحمل الفرن على نار متوسطة وحط الزيت.", null, "نار متوسطة", null, null),
      s("صب خليط البيض بالمقلاة وحطها بالفرن لين يتماسك البيض ويصير لونه ذهبي، حوالي 30 دقيقة.", "30 دقيقة", null, null, null),
    ],
    substitutions: { "جبنة فيتا مفتتة": "تكدر تبدلها بجبنة شيدر أو موزاريلا." }, source_url: "https://myplate.food/recipes/french-spinach-frittata",
  },

  // ==================== غداء ====================
  {
    name: "دجاج بالفرن بالثوم", slug: "baked-chicken", category: "غداء",
    description: "دجاج بالفرن بأبسط توابل ممكنة — ثوم وفلفل أسود بس.",
    prep_time_min: 5, cook_time_min: 60, servings: 5, difficulty: "easy",
    calories: 102, protein: 18.7, carbs: 0.8, fat: 2.2, fiber: 0.2,
    match_keywords: ["دجاج بالفرن", "دجاج مشوي بسيط"],
    ingredients: [i("صدر دجاج بدون عظم وجلد", "1", "رطل (حوالي 450غ)"), i("بودرة ثوم", "1", "ملعقة صغيرة"), i("فلفل أسود مطحون", "1", "ملعقة صغيرة"), i("ملح", null, "حسب الرغبة")],
    steps: [
      s("سخّن الفرن.", null, "175°م", null, null),
      s("حط الدجاج بصينية فرن ورش بودرة الثوم والفلفل.", null, null, null, null),
      s("اخبزه ساعة كاملة.", "60 دقيقة", null, null, "تأكد الدجاج مستوي بالكامل قبل التقديم."),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/baked-chicken",
  },
  {
    name: "دجاج بالمشمش والليمون", slug: "apricot-lemon-chicken", category: "غداء",
    description: "صدور دجاج بصلصة مشمش وليمون حلوة حامضة.",
    prep_time_min: 5, cook_time_min: 15, servings: 4, difficulty: "easy",
    calories: 222, protein: 28, carbs: 18.3, fat: 3.4, fiber: 0.4,
    match_keywords: ["دجاج بالمشمش", "دجاج حلو حامض"],
    ingredients: [i("صدر دجاج بدون عظم", "4", "حبة متوسطة"), i("كمون", "1", "ملعقة صغيرة"), i("مربى مشمش", "5", "ملعقة كبيرة (حوالي 1/3 كوب)"), i("ليمون", "1", "حبة، معصور"), i("ماي", "2", "ملعقة كبيرة")],
    steps: [
      s("افرك الدجاج بالكمون وحطه بمقلاة.", null, null, null, null),
      s("اطبخه على نار متوسطة-عالية 6 دقايق لكل وجه لين يستوي.", "6 دقايق لكل وجه", "نار متوسطة-عالية", null, null),
      s("اطلع الدجاج وخليه جنب دافي. زيد مربى المشمش وعصير الليمون والماي بنفس المقلاة وحرّك لين يتجانس.", null, null, null, null),
      s("صب الصلصة فوگ الدجاج وقدّمه دافي.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/apricot-lemon-chicken",
  },
  {
    name: "جيوب بيتا بالأفوكادو", slug: "avocado-pita-pockets", category: "غداء",
    description: "غداء خفيف وسريع، خبز بيتا محشي أفوكادو وحمص وجبنة.",
    prep_time_min: 10, cook_time_min: 0, servings: 4, difficulty: "easy",
    calories: 164, protein: 5.1, carbs: 21.8, fat: 7.4, fiber: 5.1,
    match_keywords: ["بيتا بالأفوكادو", "ساندويچ أفوكادو"],
    ingredients: [i("أفوكادو ناضج", "1", "حبة مقطعة مكعبات"), i("خبز بيتا حبوب كاملة", "2", "رغيف مقطوع نصين"), i("حمص معلب", "1/4", "كوب مصفى"), i("جبنة فيتا مفتتة", "2", "ملعقة كبيرة"), i("ملح وفلفل", null, "حسب الرغبة")],
    steps: [
      s("احشي نص جيب البيتا بالأفوكادو والحمص والجبنة بالتساوي.", null, null, null, null),
      s("سخّنه بالمايكروويف 15-20 ثانية إذا حبيت.", "15-20 ثانية", null, null, null),
      s("تبّله بالملح والفلفل وقدّمه.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/avocado-pita-pockets",
  },
  {
    name: "إنتشلادا الفاصوليا", slug: "bean-enchiladas", category: "غداء",
    description: "غداء نباتي سهل وصحي، لفائف تورتيلا محشية فاصوليا وجبنة.",
    prep_time_min: 15, cook_time_min: 20, servings: 8, difficulty: "medium",
    calories: 224, protein: 10.3, carbs: 35.1, fat: 5, fiber: 7,
    match_keywords: ["انتشلادا فاصوليا", "لفائف فاصوليا"],
    ingredients: [i("فاصوليا بينتو معلبة قليلة الصوديوم", "4", "كوب (علبتين 425غ)"), i("جبنة مونتيري جاك قليلة الدسم", "1/2", "كوب"), i("بودرة فلفل حار", "1", "ملعقة كبيرة"), i("تورتيلا (15 سم)", "8", "رغيف"), i("صلصة", null, "اختياري")],
    steps: [
      s("اهرس الفاصوليا بوعاء كبير واخلط بيها بودرة الفلفل.", null, null, null, null),
      s("لف التورتيلا بمنشفة ورقية مبللة وسخّنها بالمايكروويف 45 ثانية لين تطري.", "45 ثانية", null, null, null),
      s("وزّع خليط الفاصوليا على التورتيلا، رش الجبنة، ولف كل وحدة.", null, null, null, null),
      s("رتّبها بصينية فرن مدهونة والوجه المطوي تحت، وغطّي بالفويل.", null, null, null, null),
      s("اخبزها 20 دقيقة لين تسخن زين، وقدّمها دافية مع الصلصة.", "20 دقيقة", "175°م", null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/bean-enchiladas",
  },
  {
    name: "كساديا الفاصوليا السوداء", slug: "black-bean-quesadillas", category: "غداء",
    description: "كساديا سريعة بالفاصوليا السوداء والجبنة، تصلح غدا أو عشا.",
    prep_time_min: 10, cook_time_min: 10, servings: 8, difficulty: "easy",
    calories: 214, protein: 13.3, carbs: 20.7, fat: 8.4, fiber: 6.1,
    match_keywords: ["كساديا فاصوليا", "كساديا سوداء"],
    ingredients: [i("صلصة سالسا", "3/4", "كوب"), i("فاصوليا سوداء قليلة الصوديوم معلبة", "1", "علبة (حوالي 440غ) مصفاة"), i("جبنة مبروشة قليلة الدسم", "2", "كوب"), i("كزبرة طازجة مفرومة", "2", "ملعقة كبيرة"), i("تورتيلا (20 سم)", "4", "رغيف"), i("زيت زيتون", "1/2", "ملعقة صغيرة")],
    steps: [
      s("صفّي السالسا من السائل الزايد بمصفاة.", null, null, null, null),
      s("اخلط السالسا المصفاة مع الفاصوليا والجبنة والكزبرة بوعاء.", null, null, null, null),
      s("وزّع الخليط على نص كل تورتيلا (حوالي نص كوب لكل وحدة) واطوها.", null, null, null, null),
      s("سخّن مقلاة كبيرة على نار متوسطة-عالية وادهنها بالزيت.", null, "نار متوسطة-عالية", null, null),
      s("اطبخ التورتيلا المحشية وقلبها مرة وحدة لين تصير ذهبية ومقرمشة وتذوب الجبنة، حوالي 5 دقايق. قطّعها أرباع وقدّمها.", "5 دقايق", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/black-bean-quesadillas",
  },
  {
    name: "بوريتو الفاصوليا والرز", slug: "bean-and-rice-burritos", category: "غداء",
    description: "بوريتو بالفرن، طريقة زينة تستخدم بيها رز مطبوخ زايد عندك بالبيت.",
    prep_time_min: 10, cook_time_min: 15, servings: 8, difficulty: "medium",
    calories: 279, protein: 10, carbs: 45.1, fat: 6.4, fiber: 5.6,
    match_keywords: ["بوريتو فاصوليا", "بوريتو رز"],
    ingredients: [i("رز مطبوخ", "2", "كوب"), i("بصل صغير مفروم", "1", "حبة"), i("فاصوليا حمراء مطبوخة", "2", "كوب (أو علبة 425غ مصفاة)"), i("تورتيلا متوسطة", "8", "رغيف"), i("صلصة سالسا", "1/2", "كوب"), i("جبنة مبروشة", "1/2", "كوب")],
    steps: [
      s("سخّن الفرن.", null, "150°م", null, null),
      s("قطّع البصل قطع صغيرة وصفّي الفاصوليا من السائل.", null, null, null, null),
      s("اخلط الرز والبصل والفاصوليا بوعاء.", null, null, null, null),
      s("حط نص كوب من الخليط بنص كل تورتيلا واطوِ الجوانب حتى يتماسك.", null, null, null, null),
      s("رتّب البوريتو بصينية فرن واخبزه 15 دقيقة.", "15 دقيقة", null, null, null),
      s("صب السالسا فوگه ورش الجبنة، وقدّمه دافي.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/bean-and-rice-burritos",
  },

  // ==================== عشاء ====================
  {
    name: "دجاج بخطوتين بشوربة الدجاج", slug: "2-step-chicken", category: "عشاء",
    description: "أبسط عشاء ممكن — دجاج بصلصة شوربة الدجاج، قدّمه مع سلطة أو خضار مشوية.",
    prep_time_min: 5, cook_time_min: 20, servings: 4, difficulty: "easy",
    calories: 149, protein: 15.2, carbs: 7.1, fat: 6.1, fiber: 0.3,
    match_keywords: ["دجاج بشوربة", "دجاج بخطوتين"],
    ingredients: [i("زيت نباتي", "1", "ملعقة كبيرة"), i("صدر دجاج بدون عظم وجلد", "2", "حبة"), i("شوربة دجاج معلبة قليلة الصوديوم", "1", "علبة (300غ تقريبًا)"), i("ماي", "1/2", "كوب")],
    steps: [
      s("سخّن الزيت بمقلاة على نار متوسطة-عالية.", null, "نار متوسطة-عالية", null, null),
      s("زيد الدجاج واطبخه 10 دقايق.", "10 دقايق", null, null, null),
      s("اطلع الدجاج وخليه جنب. حرّك الشوربة والماي بنفس المقلاة لين يغلي.", null, null, null, null),
      s("رجّع الدجاج للمقلاة، خفف النار، وخله يطفي 10 دقايق زيادة لين يستوي بالكامل (165°ف داخليًا).", "10 دقايق", "نار هادئة", null, "تأكد الدجاج مستوي بالكامل قبل التقديم."),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/2-step-chicken",
  },
  {
    name: "سمك بالفرن بالطماطة والفلفل والبصل", slug: "baked-fish-tomatoes-peppers-onions", category: "عشاء",
    description: "عشاء سريع وصحي، سمك بالفرن مع خضار — يصلح لليالي المشغولة.",
    prep_time_min: 10, cook_time_min: 20, servings: 4, difficulty: "easy",
    calories: 81, protein: 16.6, carbs: 3.4, fat: 0.4, fiber: 1.3,
    match_keywords: ["سمك بالفرن", "سمك بالخضار"],
    ingredients: [i("فيليه سمك أبيض", "1", "رطل (حوالي 450غ)"), i("فلفل أخضر مقطع", "1/4", "كوب"), i("طماطة معلبة قليلة الصوديوم", "1/2", "علبة (حوالي 200غ)"), i("بصل مقطع", "1/4", "كوب"), i("أوريگانو", "1/4", "ملعقة صغيرة")],
    steps: [
      s("سخّن الفرن ودهن صينية فرن.", null, "175°م", null, null),
      s("قطّع السمك 4 قطع وحطه بالصينية.", null, null, null, null),
      s("وزّع الفلفل والطماطة والبصل والأوريگانو فوگ السمك.", null, null, null, null),
      s("اخبزه حوالي 20 دقيقة لين السمك يتقشر بالشوكة بسهولة.", "20 دقيقة", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/baked-fish-tomatoes-peppers-onions",
  },
  {
    name: "توفو بالفرن", slug: "baked-tofu", category: "عشاء",
    description: "توفو بنكهة الزنجبيل والصويا والثوم، بديل نباتي غني بالبروتين.",
    prep_time_min: 10, cook_time_min: 30, servings: 4, difficulty: "medium",
    calories: 99, protein: 10.7, carbs: 1.9, fat: 6.4, fiber: 1.1,
    match_keywords: ["توفو بالفرن", "توفو نباتي"],
    ingredients: [i("صلصة صويا قليلة الصوديوم", "2", "ملعقة كبيرة"), i("ثوم مفروم", "1", "فص"), i("زنجبيل طازج مفروم", "1", "ملعقة صغيرة"), i("زيت نباتي", "1", "ملعقة صغيرة"), i("توفو متماسك", "1", "عبوة (400غ تقريبًا)")],
    steps: [
      s("سخّن الفرن وفرش صينية فرن بفويل.", null, "175°م", null, null),
      s("صفّي التوفو من الماي ولفّه بمنشفة ورقية 5 دقايق حتى ينشف.", "5 دقايق", null, null, null),
      s("اخلط صلصة الصويا والثوم والزنجبيل والزيت بوعاء صغير.", null, null, null, null),
      s("قطّع التوفو شرائح بسمك نص سم وحطها بالصينية.", null, null, null, null),
      s("صب الخليط فوگ التوفو واقلبه بلطف حتى يتغطى الوجهين.", null, null, null, null),
      s("اخبزه 15 دقيقة، اقلبه، واخبز 15 دقيقة زيادة لين يصير ذهبي ومتماسك.", "30 دقيقة", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/baked-tofu",
  },
  {
    name: "لحم مفروم بالمعكرونة", slug: "beef-noodles", category: "عشاء",
    description: "عشاء سريع وسهل بمكونات بسيطة، قدّمه مع خضار من الفريزر لوجبة كاملة.",
    prep_time_min: 5, cook_time_min: 20, servings: 4, difficulty: "easy",
    calories: 235, protein: 19.1, carbs: 18.3, fat: 9.1, fiber: 0.9,
    match_keywords: ["لحم بالمعكرونة", "لحم مفروم بالنودلز"],
    ingredients: [i("لحم بقر مفروم قليل الدسم", "3/4", "رطل (حوالي 340غ)"), i("ماي", "1.5", "كوب"), i("نودلز بيض نيء", "2", "كوب (أو أي معكرونة)"), i("توابل حسب الرغبة", null, null), i("ملح", null, "اختياري")],
    steps: [
      s("حمّر اللحم المفروم بمقلاة كبيرة وصفّي الدهن الزايد.", null, null, null, null),
      s("زيد الماي والنودلز والتوابل وحرّك.", null, null, null, null),
      s("خله يغلي، بعدين خفف النار وخطّيه يطفي 15-20 دقيقة لين النودلز يستوي.", "15-20 دقيقة", "نار هادئة", null, null),
      s("ذوّق وزيد ملح إذا احتاج.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/beef-noodles",
  },
  {
    name: "ريش لحم خنزير بالفرن", slug: "baked-pork-chops", category: "عشاء",
    description: "ريش لحم بالفرن مع فلفل أخضر وأحمر — طبق ملوّن ولذيذ.",
    prep_time_min: 15, cook_time_min: 45, servings: 6, difficulty: "medium",
    calories: 268, protein: 41.7, carbs: 4, fat: 8.8, fiber: 0.7,
    match_keywords: ["ريش لحم بالفرن", "لحم خنزير بالفرن"],
    ingredients: [i("ريش لحم قليلة الدهن", "6", "قطعة بسمك 1 سم"), i("بصل متوسط مقطع شرائح", "1", "حبة"), i("فلفل أخضر مقطع", "1/2", "كوب"), i("فلفل أحمر مقطع", "1/2", "كوب"), i("فلفل أسود", "1/8", "ملعقة صغيرة"), i("ملح", "1/4", "ملعقة صغيرة")],
    steps: [
      s("نظّف الدهن الزايد من اللحم وحطه بصينية فرن.", null, null, null, null),
      s("فرش البصل والفلفلين فوگ اللحم ورش الملح والفلفل.", null, null, null, null),
      s("خله بالثلاجة ساعة كاملة قبل الطبخ.", "60 دقيقة", null, null, null),
      s("سخّن الفرن وغطّي الصينية واخبزها 30 دقيقة.", "30 دقيقة", "190°م", null, null),
      s("اكشف الغطا، اقلب اللحم، وغطّي بالخضار مرة ثانية، وأكمل 15 دقيقة لين الحرارة الداخلية توصل 63°م.", "15 دقيقة", null, null, "تأكد اللحم مستوي بالكامل قبل التقديم."),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/baked-pork-chops",
  },
  {
    name: "سمك بالفرن ببسطة الفويل", slug: "baked-fish", category: "عشاء",
    description: "سمك بالفرن ملفوف بالفويل — طريقة سهلة تحافظ على طراوته.",
    prep_time_min: 10, cook_time_min: 20, servings: 4, difficulty: "easy",
    calories: 138, protein: 21.2, carbs: 3.6, fat: 4.5, fiber: 0.7,
    match_keywords: ["سمك بالفويل", "سمك بالفرن بسيط"],
    ingredients: [i("فيليه سمك", "1", "رطل (وايت فيش أو تلابيا)"), i("بصل مقطع شرائح", "1", "حبة"), i("ملح", "1/4", "ملعقة صغيرة"), i("فلفل أسود", "1/4", "ملعقة صغيرة"), i("زيت نباتي", "2", "ملعقة صغيرة")],
    steps: [
      s("سخّن الفرن.", null, "175°م", null, null),
      s("حط قطعة فويل كبيرة على المنضدة وحط السمك بنصها.", null, null, null, null),
      s("وزّع البصل والملح والفلفل والزيت فوگ السمك.", null, null, null, null),
      s("اطوِ الفويل حتى يتغطى السمك بالكامل وحطه بصينية فرن.", null, null, null, null),
      s("اخبزه 15-20 دقيقة لين يتقشر السمك بالشوكة بسهولة، وقسّمه أربع حصص.", "15-20 دقيقة", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/baked-fish",
  },

  // ==================== سناك ====================
  {
    name: "أفعى الموز", slug: "fruit-snake", category: "سناك",
    description: "سناك مرح وسريع للعيال، موز بس بشكل أفعى.",
    prep_time_min: 5, cook_time_min: 0, servings: 2, difficulty: "easy",
    calories: 127, protein: 1, carbs: 29.9, fat: 0.4, fiber: 2.2,
    match_keywords: ["سناك موز", "افعى الموز"],
    ingredients: [i("موز متوسط", "2", "حبة"), i("زبيب", "4", "حبة")],
    steps: [s("قشّر الموز وقطّعه نصين طولي بسكين.", null, null, null, null), s("رتّب النصين على شكل حرف S بطبق صغير وحط الزبيب فوگهم كأعين.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/fruit-snake",
  },
  {
    name: "أرنب الإجاص", slug: "pear-rabbit", category: "سناك",
    description: "سناك فواكه لطيف على شكل أرنب، العيال يحبون يساعدون بتحضيره.",
    prep_time_min: 5, cook_time_min: 0, servings: 1, difficulty: "easy",
    calories: 151, protein: 0.9, carbs: 39.8, fat: 0.2, fiber: 4.5,
    match_keywords: ["ارنب اجاص", "سناك اجاص"],
    ingredients: [i("إجاص معلب أنصاف", "3", "حبة"), i("زبيب", "1", "ملعقة كبيرة")],
    steps: [s("رتّب نصين إجاص بالوجه المسطح تحت لتكوين الجسم.", null, null, null, null), s("قطّع من نص إجاص ثالث ذيل وأذنين وأرجل وثبتها بالجسم.", null, null, null, null), s("قطّع زبيبة نصين وحطهم عيون بالطرف الصغير.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/pear-rabbit",
  },
  {
    name: "سلحفاة التفاح", slug: "turtle-apple", category: "سناك",
    description: "سناك بسيط وممتع بس بالتفاح والبرتقال المعلب.",
    prep_time_min: 5, cook_time_min: 0, servings: 2, difficulty: "easy",
    calories: 76, protein: 0.4, carbs: 18.6, fat: 0.2, fiber: 2.4,
    match_keywords: ["سلحفاة تفاح", "سناك تفاح للعيال"],
    ingredients: [i("تفاح", "1", "حبة صغيرة أو متوسطة"), i("شرائح يوسفي مصفاة", "10", "شريحة")],
    steps: [s("اغسل التفاح وقطّعه نصين.", null, null, null, null), s("حط نص التفاح بنص طبق صغير وحط شرائح اليوسفي حوله كأرجل وذيل ورأس.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/turtle-apple",
  },
  {
    name: "موز مجفف", slug: "dried-bananas", category: "سناك",
    description: "سناك مقرمش صحي، تكدر تسويه بكمية كبيرة وتخزنه.",
    prep_time_min: 10, cook_time_min: 90, servings: 2, difficulty: "medium",
    calories: 61, protein: 0.5, carbs: 14.3, fat: 0.2, fiber: 1.1,
    match_keywords: ["موز مجفف", "چيبس موز"],
    ingredients: [i("موز", "1", "حبة"), i("عصير حامضي (ليمون أو أناناس)", null, "اختياري، لمنع الاسمرار"), i("قرفة أو توابل", null, "اختياري")],
    steps: [
      s("قطّع الموز شرائح بسمك 3-6 ملم.", null, null, null, null),
      s("غمّس الشرائح بالعصير الحامضي إذا حبيت، ورش قرفة حسب الرغبة.", null, null, null, null),
      s("رتّبها بصينية فرن أو شبكة تجفيف وحطها بالفرن على أقل حرارة ممكنة.", null, "80-95°م", null, null),
      s("جفّفها 1-3 ساعات لين تصير طرية وممطاطة ومو لزجة.", "1-3 ساعة", null, "شبكة التجفيف تخلي الموز ينشف أسرع من الصينية العادية.", null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/dried-bananas",
  },
  {
    name: "چيبس الكيل", slug: "kale-chips", category: "سناك",
    description: "چيبس مقرمش صحي، تكدر تغيّر التوابل حسب ذوقك.",
    prep_time_min: 10, cook_time_min: 12, servings: 6, difficulty: "easy",
    calories: 34, protein: 0.1, carbs: 0.2, fat: 3.6, fiber: 0.2,
    match_keywords: ["چيبس كيل", "كيل مقرمش"],
    ingredients: [i("ورق كيل (أو سبانخ)", "1", "كوب"), i("زيت زيتون", "1.5", "ملعقة كبيرة"), i("توابل حسب الرغبة", null, null)],
    steps: [
      s("سخّن الفرن.", null, "150°م", null, null),
      s("اغسل الكيل وجفّفه زين، واطلع الأوراق من الساق السميك.", null, null, "لازم ينشف زين حتى يصير مقرمش مو طري.", null),
      s("قطّعه قطع بحجم اللقمة وحطه بصينية فرن مفروشة ورق زبدة.", null, null, null, null),
      s("رش الزيت والتوابل فوگه.", null, null, null, null),
      s("اخبزه 10-15 دقيقة لين يصير مقرمش وأطرافه بنية بدون ما يحترق.", "10-15 دقيقة", null, null, "راقبه حتى ما يحترق."),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/kale-chips",
  },
  {
    name: "حمص محمص بالفرن", slug: "roasted-chickpeas-garbanzo-beans", category: "سناك",
    description: "سناك مقرمش صحي، تكدر تحطه فوگ السلطة كمان.",
    prep_time_min: 10, cook_time_min: 50, servings: 4, difficulty: "medium",
    calories: 128, protein: 5.4, carbs: 14.8, fat: 5.6, fiber: 4.8,
    match_keywords: ["حمص محمص", "حمص بالفرن"],
    ingredients: [i("حمص معلب قليل الصوديوم", "1", "علبة (425غ) مصفاة"), i("زيت كانولا", "1", "ملعقة كبيرة"), i("ملح", "1/8", "ملعقة صغيرة"), i("توابل حسب الرغبة", null, "ثوم، بابريكا، إلخ")],
    steps: [
      s("سخّن الفرن.", null, "200°م", null, null),
      s("صفّي الحمص واغسله لين يروح الرغوة، وشيل القشور الطافية.", null, null, null, null),
      s("لفّه بمنشفة نظيفة حتى ينشف زين.", null, null, null, null),
      s("حط الزيت بصينية فرن، زيد الحمص، ورش الملح والتوابل، وقلّب لين يتغطى بالكامل.", null, null, null, null),
      s("اخبزه 45-60 دقيقة وحرّكه كل 15 دقيقة — كل ما طوّلته يصير أقرمش، بس راقبه حتى ما يحترق.", "45-60 دقيقة", null, null, "راقبه حتى ما يحترق."),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/roasted-chickpeas-garbanzo-beans",
  },

  // ==================== حلويات ====================
  {
    name: "بوظة زبادي بالفراولة", slug: "fruit-yogurt-pops", category: "حلويات",
    description: "حلوة صيفية بمكونين بس، بدون طبخ ولا معدات خاصة.",
    prep_time_min: 10, cook_time_min: 0, servings: 14, difficulty: "easy",
    calories: 24, protein: 0.9, carbs: 4.4, fat: 0.3, fiber: 0.5,
    match_keywords: ["بوظة زبادي", "ايس بوب فراولة"],
    ingredients: [i("زبادي قليل الدسم بنكهة فواكه", "1", "علبة (225غ)"), i("فراولة مقطعة مجمدة", "2.5", "كوب مذابة")],
    steps: [
      s("اخلط الزبادي والفراولة سوا بوعاء.", null, null, null, null),
      s("صبه بأكواب ورقية صغيرة.", null, null, null, null),
      s("جمّده 30 دقيقة، بعدين غرز عود بوظة بنص كل كوب.", "30 دقيقة", null, null, null),
      s("جمّده طول الليل لين يتماسك بالكامل. لتقديمه، قشّر الكوب الورقي.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/fruit-yogurt-pops",
  },
  {
    name: "بوظة موز سهلة", slug: "easiest-banana-ice-cream", category: "حلويات",
    description: "لا ترمي الموز الناضج زيادة — جمّده وخفقه تطلع بوظة كريمية.",
    prep_time_min: 10, cook_time_min: 0, servings: 3, difficulty: "easy",
    calories: 108, protein: 1.3, carbs: 24.6, fat: 0.4, fiber: 1.8,
    match_keywords: ["بوظة موز", "ايس كريم موز"],
    ingredients: [i("موز ناضج", "2.5", "حبة"), i("حليب 1%", "3", "ملعقة كبيرة"), i("شراب شوكولاتة", null, "اختياري")],
    steps: [
      s("قشّر الموز وقطّعه شرائح، وحطه بصينية مفروشة بلاستيك وجمّده طول الليل.", null, null, null, null),
      s("حط شرائح الموز المجمد بخلاط أو محضّرة طعام مع رشة حليب.", null, null, null, null),
      s("اخفقه لين يصير كريمي ونعيم — تحتاج توقف وتكشط الجوانب كم مرة.", null, null, "تحتاج شوي وقت لين يصير قوام البوظة الطرية.", null),
      s("قدّمه بكاسة صغيرة مع خط رقيق من شراب الشوكولاتة إذا حبيت.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/easiest-banana-ice-cream",
  },
  {
    name: "موس شوكولاتة سريع", slug: "instant-chocolate-mousse", category: "حلويات",
    description: "حلوة سريعة وغنية بالبروتين — سر النعومة توفو حريري.",
    prep_time_min: 10, cook_time_min: 0, servings: 4, difficulty: "easy",
    calories: 183, protein: 10.4, carbs: 23.9, fat: 5.8, fiber: 1.1,
    match_keywords: ["موس شوكولاتة", "بودينغ شوكولاتة"],
    ingredients: [i("خليط بودينغ شوكولاتة سريع التحضير", "1", "علبة (110غ)"), i("حليب صويا بارد", "1.25", "كوب"), i("توفو حريري", "1", "عبوة (400غ)")],
    steps: [
      s("اخفق خليط البودينغ وحليب الصويا بالخلاط على سرعة متوسطة 15 ثانية لين يتجانس.", "15 ثانية", null, null, null),
      s("زيد التوفو الحريري واخفق مرة ثانية، واكشط الجوانب حتى يختلط بالكامل.", null, null, null, null),
      s("صبه بـ4 كاسات تقديم.", null, null, null, null),
      s("حطه بالثلاجة ساعتين على الأقل قبل التقديم.", "ساعتين على الأقل", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/instant-chocolate-mousse",
  },
  {
    name: "فروزن يوگرت أناناس وبرتقال", slug: "pineapple-orange-frozen-yogurt", category: "حلويات",
    description: "حلوة استوائية منعشة تخليك بارد بأيام الصيف الحارة.",
    prep_time_min: 10, cook_time_min: 0, servings: 3, difficulty: "medium",
    calories: 101, protein: 5.2, carbs: 19.8, fat: 0.4, fiber: 0.9,
    match_keywords: ["فروزن يوگرت", "زبادي مجمد بالأناناس"],
    ingredients: [i("زبادي فانيلا خالي الدسم", "1", "كوب"), i("قطع أناناس طازج أو معلب", "1", "كوب"), i("عصير برتقال", "1/2", "كوب")],
    steps: [
      s("حط الزبادي والأناناس بكيس بلاستيك وافرده مسطح، وجمّده طول الليل.", null, null, null, null),
      s("اخلط الزبادي والأناناس المجمدين مع العصير بمحضّرة طعام أو خلاط لين يتنعّم.", null, null, null, null),
      s("قدّمه فورًا أو رجّعه للفريزر لين يتماسك (لحد ساعة)، وحرّكه بين فترة وفترة.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/pineapple-orange-frozen-yogurt",
  },
  {
    name: "بودينغ الموز", slug: "banana-pudding", category: "حلويات",
    description: "حلوة سهلة بخليط بودينغ جاهز وزبادي وموز طازج.",
    prep_time_min: 10, cook_time_min: 0, servings: 8, difficulty: "easy",
    calories: 116, protein: 3.8, carbs: 23.6, fat: 0.7, fiber: 0.5,
    match_keywords: ["بودينغ موز", "حلاوة موز بالزبادي"],
    ingredients: [i("خليط بودينغ سريع (موز أو فانيلا)", "1", "علبة (95غ)"), i("حليب خالي الدسم", "2", "كوب"), i("زبادي سادة خالي الدسم", "1", "علبة (225غ)"), i("موز متوسط مقطع", "2", "حبة")],
    steps: [
      s("اخلط خليط البودينغ والحليب بوعاء وحرّك بملعقة أو خفاقة دقيقتين.", "2 دقيقة", null, null, null),
      s("امزج الزبادي بلطف مع خليط البودينغ.", null, null, null, null),
      s("حطه بالثلاجة 30 دقيقة.", "30 دقيقة", null, null, null),
      s("رتّب طبقة موز بقاع 8 كاسات تقديم، وصب البودينغ فوگها، وزيّنها بشرائح موز إضافية.", null, null, null, null),
      s("خله بالثلاجة على الأقل 5 دقايق قبل التقديم — كل ما طوّلته الطعم أحلى.", "5 دقايق على الأقل", null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/banana-pudding",
  },
  {
    name: "بودينغ خبز بالتوت", slug: "berry-bread-pudding", category: "حلويات",
    description: "بودينغ خبز بدون طبخ — طبقات خبز وتوت وزبادي تتماسك بالثلاجة.",
    prep_time_min: 15, cook_time_min: 0, servings: 2, difficulty: "medium",
    calories: 159, protein: 5.4, carbs: 31, fat: 2.1, fiber: 5.4,
    match_keywords: ["بودينغ خبز", "حلاوة خبز بالتوت"],
    ingredients: [i("توت (بلوبيري أو فراولة أو توت العليق) مذاب", "1.5", "كوب"), i("خبز قمح كامل بدون قشرة", "5", "شريحة"), i("سكر", null, "1/2 ملعقة صغيرة، اختياري"), i("زبادي فانيلا قليل الدسم", null, "للتقديم، اختياري")],
    steps: [
      s("امزج التوت مع السكر إذا حبيت.", null, null, null, null),
      s("حط طبقة توت بقاع وعاء صغير عميق، وغطّيها بطبقة خبز، وكرر الطبقات لين يخلص الوعاء منتهي بطبقة خبز.", null, null, null, null),
      s("غطّي الوعاء بغلاف بلاستيك وحط فوگه طبق أو وعاء يضغط على الطبقات.", null, null, null, null),
      s("حطه بالثلاجة طول الليل. تأكد العصير ما يفيض من فوگ.", null, null, null, null),
      s("قدّمه مع ملعقة زبادي فانيلا فوگه.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/berry-bread-pudding",
  },

  // ==================== مشروبات باردة ====================
  {
    name: "ليموناضة طازجة", slug: "lemonade", category: "مشروبات باردة",
    description: "كاسة ليموناضة طازجة بحبة ليمون وحدة بس، مثالية بيوم حر.",
    prep_time_min: 5, cook_time_min: 0, servings: 1, difficulty: "easy",
    calories: 60, protein: 0.2, carbs: 15.7, fat: 0.1, fiber: 0.1,
    match_keywords: ["ليموناضة", "عصير ليمون"],
    ingredients: [i("ليمون", "1", "حبة"), i("ماي", "3/4", "كوب"), i("سكر", "1", "ملعقة كبيرة")],
    steps: [
      s("قطّع الليمون نصين عرضي واعصره.", null, null, null, null),
      s("صب العصير بكاسة وزيد الماي.", null, null, null, null),
      s("زيد السكر وحرّك لين يذوب.", null, null, "تكدر تبدّل النكهة بشوية عصير ليم أو برتقال بدل السكر.", null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/lemonade",
  },
  {
    name: "مشروب الشمام البارد", slug: "cantaloupe-cooler", category: "مشروبات باردة",
    description: "مشروب منعش بعصير البرتقال والشمام الحلو — سويه بأي فاكهة تحبها.",
    prep_time_min: 10, cook_time_min: 0, servings: 8, difficulty: "easy",
    calories: 75, protein: 1.2, carbs: 16.5, fat: 0.4, fiber: 0.8,
    match_keywords: ["مشروب شمام", "عصير شمام"],
    ingredients: [i("شمام ناضج", "1", "حبة"), i("عصير برتقال بارد", "2.5", "كوب"), i("سكر", "2", "ملعقة كبيرة"), i("ثلج مجروش", null, "حسب الرغبة")],
    steps: [
      s("قطّع الشمام نصين، اطلع البذور وقشّره وارمي القشر.", null, null, null, null),
      s("قطّعه مكعبات وحطه بالخلاط مع نص كوب عصير برتقال، واخفقه لين ينعّم.", null, null, null, null),
      s("صب الخليط بإبريق وزيد باقي العصير والسكر، وحرّك لين يذوب السكر.", null, null, null, null),
      s("صبه بكاسات فيها ثلج مجروش.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/cantaloupe-cooler",
  },
  {
    name: "سموذي فواكه", slug: "fruit-smoothie", category: "مشروبات باردة",
    description: "جرّب فواكه وعصائر مختلفة بهذا السموذي اللذيذ.",
    prep_time_min: 5, cook_time_min: 0, servings: 2, difficulty: "easy",
    calories: 209, protein: 7, carbs: 40.2, fat: 2.2, fiber: 2.4,
    match_keywords: ["سموذي فواكه", "عصير مخفوق"],
    ingredients: [i("موز متوسط", "1", "حبة"), i("خوخ طازج (أو فراولة)", "1", "كوب"), i("زبادي فانيلا قليل الدسم", "1", "علبة (225غ)"), i("عصير فواكه 100%", "1/2", "كوب")],
    steps: [s("حط كل المكونات بالخلاط.", null, null, null, null), s("اخفقه على أعلى سرعة لين يتنعّم.", null, null, null, null), s("صبه بكاسين وقدّمه فورًا.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/fruit-smoothie",
  },
  {
    name: "مشروب الخوخ البارد", slug: "peach-cooler", category: "مشروبات باردة",
    description: "مشروب حلو حامض بالخوخ والحليب، جمّد الخوخ قبلها بساعة ليصير أبرد.",
    prep_time_min: 5, cook_time_min: 0, servings: 2, difficulty: "easy",
    calories: 155, protein: 8.8, carbs: 25.3, fat: 2.4, fiber: 1.5,
    match_keywords: ["مشروب خوخ", "عصير خوخ بالحليب"],
    ingredients: [i("حليب قليل الدسم 1%", "2", "كوب"), i("خوخ معلب بعصيره مصفى (أو طازج)", "1", "كوب"), i("عصير ليمون", "1/2", "ملعقة صغيرة"), i("جوزة الطيب", null, "رشة، اختياري")],
    steps: [s("حط كل المكونات بالخلاط واخفقها زين.", null, null, null, null), s("رش جوزة الطيب فوگه إذا حبيت وقدّمه بارد.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/peach-cooler",
  },
  {
    name: "باتيدو (سموذي الباباظ)", slug: "batido-smoothie", category: "مشروبات باردة",
    description: "سموذي منعش بالباباظ والموز والزبادي، يصلح فطور أو أي وقت باليوم.",
    prep_time_min: 5, cook_time_min: 0, servings: 4, difficulty: "easy",
    calories: 135, protein: 4.1, carbs: 27.5, fat: 1.3, fiber: 2.5,
    match_keywords: ["باتيدو", "سموذي باباظ"],
    ingredients: [i("قطع باباظ طازجة أو مجمدة", "2", "كوب"), i("موز ناضج جدًا مقطع", "2", "حبة"), i("زبادي سادة قليل الدسم", "1", "كوب"), i("ثلج مكعبات", "1", "كوب")],
    steps: [s("حط كل المكونات بالخلاط وسكّره زين.", null, null, null, null), s("اخفقه على سرعة متوسطة لين يتكسر الثلج وينعّم الخليط، حوالي دقيقة.", "1 دقيقة", null, null, null), s("قدّمه فورًا أو غطّيه وحطه بالثلاجة لحد 4 ساعات.", null, null, null, null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/batido-smoothie",
  },
  {
    name: "سموذي التوت المشكل", slug: "very-berry-smoothie", category: "مشروبات باردة",
    description: "سموذي بفراولة وتوت عليق وأناناس وموز — كوبين فواكه بكل كاسة.",
    prep_time_min: 5, cook_time_min: 0, servings: 2, difficulty: "easy",
    calories: 209, protein: 6.3, carbs: 46.9, fat: 0.9, fiber: 8.7,
    match_keywords: ["سموذي توت", "عصير توت مشكل"],
    ingredients: [i("فراولة مجمدة", "1", "كوب"), i("توت عليق مجمد", "1", "كوب"), i("قطع أناناس", "1", "كوب"), i("موز", "1", "حبة"), i("حليب خالي الدسم", "1", "كوب"), i("ثلج", "1.5", "كوب")],
    steps: [s("قشّر الموز وقطّعه.", null, null, null, null), s("حط كل المكونات بالخلاط.", null, null, null, null), s("اخفقه لين يتنعّم وقدّمه فورًا.", null, null, "تكدر تصبه بقوالب ثلج وتجمده لفطور سريع بالأسبوع.", null)],
    substitutions: {}, source_url: "https://myplate.food/recipes/very-berry-smoothie",
  },
  {
    name: "أورتشاتا", slug: "horchata", category: "مشروبات باردة",
    description: "مشروب حلو وكريمي، يصير زين مع أكل حار.",
    prep_time_min: 10, cook_time_min: 0, servings: 5, difficulty: "medium",
    calories: 272, protein: 3.9, carbs: 60.9, fat: 0.7, fiber: 0.9,
    match_keywords: ["اورتشاتا", "مشروب الرز"],
    ingredients: [i("رز أبيض طويل الحبة نيء", "1", "كوب"), i("ماي", "5", "كوب"), i("حليب 1%", "1/2", "كوب"), i("فانيلا", "1/2", "ملعقة كبيرة"), i("قرفة مطحونة", "1/2", "ملعقة كبيرة"), i("سكر", "2/3", "كوب")],
    steps: [
      s("حط الرز والماي بالخلاط واخفقه دقيقة لين يبدأ الرز يتكسر.", "1 دقيقة", null, null, null),
      s("خله يرتاح بدرجة حرارة الغرفة حوالي 3 ساعات.", "3 ساعات", null, null, null),
      s("صفّي ماي الرز بإبريق وارمي الرز.", null, null, null, null),
      s("زيد الحليب والفانيلا والقرفة والسكر وحرّك.", null, null, null, null),
      s("برّده بالثلاجة وحرّكه قبل التقديم فوگ ثلج.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/horchata",
  },

  // ==================== مشروبات حارة ====================
  {
    name: "كافيه موكا", slug: "cafe-mocha", category: "مشروبات حارة",
    description: "قهوة بالشوكولاتة الدافية، زيّنها بشوية قرفة.",
    prep_time_min: 5, cook_time_min: 5, servings: 2, difficulty: "easy",
    calories: 65, protein: 6.2, carbs: 11.6, fat: 1.5, fiber: 3.7,
    match_keywords: ["كافيه موكا", "قهوة بالشوكولاتة"],
    ingredients: [i("حليب بودرة خالي الدسم", "1/3", "كوب"), i("ماي", "1", "كوب"), i("قهوة محضّرة", "1", "كوب"), i("خليط شوكولاتة ساخنة", "4", "ملعقة كبيرة"), i("كريمة خفق لايت", null, "اختياري"), i("قرفة", null, "اختياري")],
    steps: [
      s("سخّن الحليب المذاب بالماي بقدر صغير لين يصير دافي — لا تخليه يغلي.", null, "نار هادئة", null, "لا تخليه يغلي."),
      s("زيد القهوة وخليط الشوكولاتة وحرّك زين وسخّنه للدرجة اللي تحبها.", null, null, null, null),
      s("وزّعه على كاستين وزيّنه بالكريمة والقرفة إذا حبيت.", null, null, null, null),
    ],
    substitutions: {}, source_url: "https://myplate.food/recipes/cafe-mocha",
  },
];
